// Projects Data
export const projects = [
  {
    id: 1,
    title: "E-commerce Platform",
    description:
      "Full-stack e-commerce solution with React, Node.js, and MongoDB",
    category: "Web App",
    technologies: ["React", "Node.js", "MongoDB", "Express", "JWT", "Stripe"],
    image: "/images/ecommerce-project.jpg",
    liveUrl: "https://ecommerce-demo.example.com",
    githubUrl: "https://github.com/nazmulh24/ecommerce-platform",
    featured: true,
    status: "completed",
    views: 2847,
    likes: 156,
    completedDate: "2024-08-15",
  },
  {
    id: 2,
    title: "Task Management App",
    description:
      "Collaborative task management application with real-time updates",
    category: "Web App",
    technologies: ["Vue.js", "Socket.io", "PostgreSQL", "Docker"],
    image: "/images/task-management.jpg",
    liveUrl: "https://taskmanager-demo.example.com",
    githubUrl: "https://github.com/nazmulh24/task-manager",
    featured: true,
    status: "completed",
    views: 1923,
    likes: 89,
    completedDate: "2024-07-22",
  },
  {
    id: 3,
    title: "Weather Prediction API",
    description: "Machine learning-powered weather prediction REST API",
    category: "API",
    technologies: ["Python", "FastAPI", "TensorFlow", "Redis", "Docker"],
    image: "/images/weather-api.jpg",
    githubUrl: "https://github.com/nazmulh24/weather-api",
    featured: false,
    status: "completed",
    views: 1456,
    likes: 67,
    completedDate: "2024-06-10",
  },
  {
    id: 4,
    title: "Mobile Banking App",
    description:
      "Secure mobile banking application with biometric authentication",
    category: "Mobile App",
    technologies: ["React Native", "Firebase", "Plaid API", "Biometric"],
    image: "/images/banking-app.jpg",
    featured: false,
    status: "in-progress",
    views: 1234,
    likes: 45,
    completedDate: null,
  },
];

// Blog Posts Data
export const blogPosts = [
  {
    id: 1,
    title: "Modern Authentication with JWT",
    slug: "modern-authentication-jwt",
    excerpt:
      "Learn how to implement secure JWT authentication in your applications",
    content: "Full blog post content here...",
    category: "Security",
    tags: ["JWT", "Authentication", "Security", "Node.js"],
    author: "Nazmul Hossain",
    publishedDate: "2024-09-20",
    readTime: "8 min read",
    views: 1932,
    likes: 78,
    featured: true,
    image: "/images/jwt-blog.jpg",
  },
  {
    id: 2,
    title: "Microservices Architecture Guide",
    slug: "microservices-architecture-guide",
    excerpt:
      "Complete guide to designing and implementing microservices architecture",
    content: "Full blog post content here...",
    category: "Architecture",
    tags: ["Microservices", "Architecture", "Docker", "Kubernetes"],
    author: "Nazmul Hossain",
    publishedDate: "2024-09-15",
    readTime: "12 min read",
    views: 1654,
    likes: 92,
    featured: true,
    image: "/images/microservices-blog.jpg",
  },
  {
    id: 3,
    title: "React Performance Optimization",
    slug: "react-performance-optimization",
    excerpt: "Best practices for optimizing React application performance",
    content: "Full blog post content here...",
    category: "Frontend",
    tags: ["React", "Performance", "Optimization", "JavaScript"],
    author: "Nazmul Hossain",
    publishedDate: "2024-09-10",
    readTime: "10 min read",
    views: 1423,
    likes: 65,
    featured: false,
    image: "/images/react-performance.jpg",
  },
];

// Skills Data
export const skills = {
  frontend: [
    { name: "React", level: 95, category: "Framework" },
    { name: "Vue.js", level: 88, category: "Framework" },
    { name: "JavaScript", level: 94, category: "Language" },
    { name: "TypeScript", level: 89, category: "Language" },
    { name: "HTML5", level: 96, category: "Markup" },
    { name: "CSS3", level: 92, category: "Styling" },
    { name: "Sass/SCSS", level: 87, category: "Styling" },
  ],
  backend: [
    { name: "Node.js", level: 91, category: "Runtime" },
    { name: "Python", level: 85, category: "Language" },
    { name: "Express.js", level: 89, category: "Framework" },
    { name: "FastAPI", level: 78, category: "Framework" },
    { name: "GraphQL", level: 74, category: "API" },
    { name: "REST APIs", level: 92, category: "API" },
  ],
  database: [
    { name: "MongoDB", level: 87, category: "NoSQL" },
    { name: "PostgreSQL", level: 83, category: "SQL" },
    { name: "Redis", level: 79, category: "Cache" },
    { name: "MySQL", level: 81, category: "SQL" },
  ],
  tools: [
    { name: "Docker", level: 85, category: "DevOps" },
    { name: "Git", level: 94, category: "Version Control" },
    { name: "AWS", level: 78, category: "Cloud" },
    { name: "Kubernetes", level: 68, category: "DevOps" },
  ],
};
