// Recent Activities Data
export const recentActivities = [
  {
    id: 1,
    type: "project",
    title: "E-commerce Platform Deployed",
    description:
      "Successfully deployed React + Node.js e-commerce platform to AWS",
    time: "2 hours ago",
    icon: "Assignment",
    color: "#00d4ff",
    status: "completed",
  },
  {
    id: 2,
    type: "blog",
    title: "Published: Modern Authentication with JWT",
    description: "New blog post about implementing secure JWT authentication",
    time: "1 day ago",
    icon: "Article",
    color: "#4caf50",
    status: "published",
  },
  {
    id: 3,
    type: "certification",
    title: "AWS Solutions Architect Certified",
    description: "Achieved AWS Solutions Architect Associate certification",
    time: "3 days ago",
    icon: "EmojiEvents",
    color: "#ff9800",
    status: "achieved",
  },
  {
    id: 4,
    type: "project",
    title: "Mobile App Update Released",
    description: "Version 2.1.0 of React Native app with new features",
    time: "5 days ago",
    icon: "Code",
    color: "#e91e63",
    status: "released",
  },
  {
    id: 5,
    type: "collaboration",
    title: "New Client Project Started",
    description: "Kickoff meeting completed for fintech dashboard project",
    time: "1 week ago",
    icon: "Work",
    color: "#9c27b0",
    status: "started",
  },
];

// Performance Metrics Data
export const performanceMetrics = [
  {
    title: "Page Load Speed",
    score: 94,
    status: "Excellent",
    color: "#4caf50",
    icon: "Speed",
    improvement: "+5%",
    details: "Average load time: 1.2s",
  },
  {
    title: "SEO Score",
    score: 87,
    status: "Very Good",
    color: "#2196f3",
    icon: "Public",
    improvement: "+12%",
    details: "Google PageSpeed Score",
  },
  {
    title: "Accessibility",
    score: 91,
    status: "Excellent",
    color: "#4caf50",
    icon: "Security",
    improvement: "+8%",
    details: "WCAG 2.1 AA Compliant",
  },
  {
    title: "Mobile Friendly",
    score: 96,
    status: "Perfect",
    color: "#4caf50",
    icon: "Language",
    improvement: "+3%",
    details: "Responsive across all devices",
  },
];

// Action Center Recommendations
export const actionCenterItems = [
  {
    id: 1,
    title: "Update Portfolio Images",
    description: "Add high-quality screenshots of your latest projects",
    priority: "high",
    category: "content",
    color: "#e91e63",
    icon: "PhotoLibrary",
    estimated: "2 hours",
  },
  {
    id: 2,
    title: "Write New Blog Post",
    description: "Share your experience with microservices architecture",
    priority: "medium",
    category: "content",
    color: "#ff9800",
    icon: "Article",
    estimated: "4 hours",
  },
  {
    id: 3,
    title: "Optimize SEO Keywords",
    description: "Research and implement better keywords for visibility",
    priority: "medium",
    category: "seo",
    color: "#2196f3",
    icon: "TrendingUp",
    estimated: "3 hours",
  },
  {
    id: 4,
    title: "GitHub Repository Cleanup",
    description: "Archive old repositories and update READMEs",
    priority: "low",
    category: "maintenance",
    color: "#4caf50",
    icon: "GitHub",
    estimated: "1 hour",
  },
];
